import ImgSrc from '../config/imgSrc';

export default class FlokShare {
	// 用户头像
	avatar = null;
	nickName = null;

	constructor(avatar, nickName) {
		this.avatar = avatar || ImgSrc.HOME_AVATAR;
		this.nickName = nickName || '柠檬酱';
		this.title = '普法总动员';
		this.content = '坚信, 劳动最光荣';
		this.ch = '获得称号:社区达人';
	}
	palette() {
		return {
			width: '1000px',
			height: '1400px',
			background: 'rgba(0,0,0,0)',
			views: [
				{
					type: 'image',
					url: ImgSrc.HAPPY_SHARE_BG,
					css: {
						width: '1000px',
						height: '1400px',
						top: '0px',
						left: '0px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				{
					type: 'image',
					url: ImgSrc.PALETTE_FOLK_LOGO,
					css: {
						width: '200px',
						height: '200px',
						top: '1180px',
						left: '29px',
						rotate: '0',
						borderRadius: '20px',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				{
					type: 'text',
					text: this.title,
					css: {
						color: '#fff',
						background: 'rgba(0,0,0,0)',
						width: '668px',
						height: '70.785px',
						top: '1215px',
						left: '250px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						padding: '0px',
						fontSize: '49.5px',
						fontWeight: 'normal',
						maxLines: '2',
						lineHeight: '71.42850000000001px',
						textStyle: 'fill',
						textDecoration: 'none',
						fontFamily: '',
						textAlign: 'left',
					},
				},
				{
					type: 'text',
					text: this.content,
					css: {
						color: 'rgba(255,255,255, 0.6)',
						background: 'rgba(0,0,0,0)',
						width: '668px',
						height: '55.769999999999996px',
						top: '1300px',
						left: '250px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						padding: '0px',
						fontSize: '39px',
						fontWeight: 'normal',
						maxLines: '2',
						lineHeight: '56.27700000000001px',
						textStyle: 'fill',
						textDecoration: 'none',
						fontFamily: '',
						textAlign: 'left',
					},
				},
				{
					type: 'rect',
					css: {
						background: '#fff',
						width: '249px',
						height: '249px',
						top: '1124px',
						left: '728px',
						rotate: '0',
						borderRadius: '13px',
						shadow: '',
						color: '#fff',
					},
				},
				{
					type: 'image',
					url: ImgSrc.PALETTE_FOLK_CODE,
					css: {
						width: '218px',
						height: '218px',
						top: '1143px',
						left: '744px',
						rotate: '0',
						borderRadius: '13px',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				// 头像部分
				{
					type: 'rect',
					css: {
						background: 'rgba(0,0,0,1)',
						width: '226px',
						height: '226px',
						top: '76px',
						left: '387px',
						rotate: '0',
						borderRadius: '234px',
						borderWidth: '12px',
						borderColor: '#31a34d',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				{
					type: 'image',
					url: this.avatar,
					css: {
						width: '218px',
						height: '218px',
						top: '80px',
						left: '391px',
						rotate: '0',
						borderRadius: '234px',
						borderWidth: '10px',
						borderColor: '#fff',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				{
					type: 'image',
					url: ImgSrc.HAPPY_SHARE_XZ,
					css: {
						width: '721.5px',
						height: '181.5px',
						top: '414px',
						left: '141px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '',
						shadow: '',
						mode: 'scaleToFill',
					},
				},
				{
					type: 'text',
					text: this.ch,
					css: {
						color: '#fff000',
						background: 'rgba(0,0,0,0)',
						width: '668px',
						height: '85.79999999999998px',
						top: '460px',
						left: '293px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						padding: '0px',
						fontSize: '60px',
						fontWeight: 'normal',
						maxLines: '2',
						lineHeight: '86.58000000000001px',
						textStyle: 'fill',
						textDecoration: 'none',
						fontFamily: '',
						textAlign: 'left',
					},
				},
				{
					type: 'rect',
					css: {
						background: '#fff',
						width: '295.5px',
						height: '85px',
						top: '330px',
						left: '352.5px',
						rotate: '0',
						borderRadius: '50px',
						shadow: '',
						color: '#fff',
					},
				},
				{
					type: 'text',
					text: this.nickName,
					css: {
						color: '#31a34d',
						background: 'rgba(0,0,0,0)',
						width: '295.5px',
						height: '57.19999999999999px',
						top: '347px',
						left: '352.5px',
						rotate: '0',
						borderRadius: '',
						borderWidth: '',
						borderColor: '#000000',
						shadow: '',
						padding: '0px',
						fontSize: '40px',
						fontWeight: 'normal',
						maxLines: '2',
						lineHeight: '57.72000000000001px',
						textStyle: 'fill',
						textDecoration: 'none',
						fontFamily: '',
						textAlign: 'center',
					},
				},
			],
		};
	}
}
